In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import matplotlib.pyplot as plt

# Step 1: Load the dataset
iris = load_iris()
X = iris.data  # Features (sepal length, sepal width, petal length, petal width)
y = iris.target.reshape(-1, 1)  # Target labels (0, 1, 2)

# Step 2: Preprocess the data
# One-hot encode the target labels
encoder = OneHotEncoder(sparse_output=False)
y_encoded = encoder.fit_transform(y)  # Convert labels to one-hot encoded format

print("Before encoding")
print(y[1:10])
print("After One hot encoding")
print(y_encoded[1:10])


# Standardize features (important for NN training)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split into training & test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

# Step 3: Build a Neural Network Model
model = keras.Sequential([
    keras.layers.Dense(8, activation='relu', input_shape=(X_train.shape[1],)),  # Hidden layer with 8 neurons
    keras.layers.Dense(8, activation='relu'),  # Additional hidden layer
    keras.layers.Dense(3, activation='softmax')  # Output layer (3 classes)
])

# Step 4: Compile the Model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Step 5: Train the Model
history = model.fit(X_train, y_train, epochs=100, batch_size=5, validation_split=0.1, verbose=1)

# Step 6: Evaluate the Model
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=1)
print(f"Test Accuracy: {test_acc:.4f}")


# Step 8: Make Predictions
sample_data = np.array([[5.1, 3.5, 1.4, 0.2]])  # Example: A new flower
sample_data_scaled = scaler.transform(sample_data)  # Scale it
predictions = model.predict(sample_data_scaled)

# Decode prediction
predicted_class = np.argmax(predictions)
print(f"Predicted Class: {iris.target_names[predicted_class]}")


Before encoding
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
After One hot encoding
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Epoch 1/100


/Users/tkmagesh77/Documents/Training/Nutanix-Beginner-ML-Mar-2025/ML_Beginner_env/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.6507 - loss: 0.9783 - val_accuracy: 0.5000 - val_loss: 1.0570
Epoch 2/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6605 - loss: 0.9169 - val_accuracy: 0.5000 - val_loss: 1.0176
Epoch 3/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6838 - loss: 0.8800 - val_accuracy: 0.5833 - val_loss: 0.9767
Epoch 4/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6468 - loss: 0.8164 - val_accuracy: 0.5833 - val_loss: 0.9387
Epoch 5/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6936 - loss: 0.7826 - val_accuracy: 0.5833 - val_loss: 0.9009
Epoch 6/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6154 - loss: 0.7820 - val_accuracy: 0.6667 - val_loss: 0.8553
Epoch 7/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6651 - loss: 0.7280 - val_accuracy: 0.7500 - val_loss: 0.8179
Epoch 8/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7192 - loss: 0.6623 - val_accuracy: 0.7500 - val_loss: